### ISSUE TITLE
Home page change?

### ISSUE THREAD

**Issue by keaza** [vityabond/hopebilling#10]
Hey guys,

Where abouts do you change the home page, i have tried to make mutiple home.php with my template i wish to use but cant find the correct file or location to set, as i dont wish to have the bills to be my home page, i have found a redirect, but wish to intergrate my theme into the main site and get the users to login upon registering or have a seperate option, do not wish to have the Billing system on its own would rather try and keep the whole thing under one roof 

Any advise would be great

**Comment by vityabond** [comment]
Hi, you can change it in HomeController:
Tools::redirect('/bills'); -> Tools::redirect('/page/yourpage');

Create own page you can in admin panel.

**Comment by keaza** [comment]
is there any way to use the index.php file?

**Comment by keaza** [comment]
As i do not wish for the users to login when the come to my website.

**Comment by sohamb03** [comment]
Put the contents of `index.php` in something like `client.php` and then update the `.htaccess` and other files (if any) mentioning `index.php` with the new file name accordingly.
