### ISSUE TITLE
Cannot make key.lic and tmp.lic writable

### ISSUE THREAD

**Issue by gamingdna** [vityabond/hopebilling#12]
While installing hopebilling, in the 2nd step, I cannot get key.lic and tmp.lic to be writable. 
Please help me.

**Comment by sohamb03** [comment]
Set the permissions to 777 for both the files, although I doubt the two files are required anymore. 

Let's wait for a response from @vityabond, he just be releasing a new version of HopeBilling as the install directory needs some updates.

**Comment by gamingdna** [comment]
This has to do with something else entirely. I have made every file 777 but still, this error persists. This has to something with the absence of these files.

**Comment by sohamb03** [comment]
Umm, BTW you'll have to create those two files in the same directory as the HopeBilling installation. And then set the perms of the two files to 777.

**Comment by gamingdna** [comment]
Thank you. It fixed the issue.  Sorry for the stupid question and wasting your time.

**Comment by sohamb03** [comment]
No problem 👍. Don't ever think your question is stupid. We all start learning somewhere. Glad you sorted the issue. Happy to help! :-)
