### ISSUE TITLE
Error after giving SQL details

### ISSUE THREAD

**Issue by gamingdna** [vityabond/hopebilling#13]
I am facing the following issue after I successfully enter my server's SQL details.

`
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'date' in /home/tests/public_html/core/classes/System/Db/Schema/Table.php:117 Stack trace: #0 /home/tests/public_html/core/classes/System/Db/Schema/Table.php(117): PDOStatement->execute() #1 /home/tests/public_html/core/classes/System/Db/Schema/Schema.php(20): System\Db\Schema\Table->create() #2 /home/tests/public_html/app/controllers/InstallController.php(211): System\Db\Schema\Schema::create('hosting_account...', Object(Closure)) #3 /home/tests/public_html/app/controllers/InstallController.php(46): InstallController->actionDb() #4 /home/tests/public_html/core/classes/System/Router.php(148): InstallController->run('actionIndex', Array, 'install') #5 /home/tests/public_html/index.php(28): System\Router->run() #6 {main} thrown in /home/tests/public_html/core/classes/System/Db/Schema/Table.php on line 117`

**Comment by spike99** [comment]
I have the same problem. 
I finally, I instaled script.
 Then there were problems: Deprecated: Function mcrypt_module...
I use php 7.2

**Comment by sohamb03** [comment]
@gamingdna I have a feeling that has something to do with the integrity of the DB schema. Try the installation again with a new database which is completely empty. 

@spike99 That's is bcuz `mcypt` PHP extension is deprecated in PHP >=7.1, so you'll need to use a lower version preferably 5.6 cuz 7.0 is buggy. 

There's another way, @vityabond recently updated the repo replacing `mcrypt` with `OpenSSL`, so it should be possible to clone the repo and use the `install` directory from HopeBilling v1.0 to do the installation unless and otherwise there are some new requirements. I've not heard back from him in a while, but let's hope he replies soon. :-) For now using PHP 5.6 is enough to eliminate those error messages.

**Comment by vityabond** [comment]
hi guys!
Use version from git, all there issues were fixed

**Comment by spike99** [comment]
data issues in core/classes/System/Db/Schema/Table.php
invalid data 0000 00 00

after solving we have 
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'admin_hope.bm_hosting_accounts.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /home/admin/web/hope.domain.com/public_html/core/classes/System/ObjectModel.php:655 Stack trace: #0 /home/admin/web/hope.domain.com/public_html/core/classes/System/ObjectModel.php(655): PDOStatement->execute(Array) #1 /home/admin/web/hope.domain.com/public_html/app/controllers/admin/HomeController.php(51): System\ObjectModel->getRows() #2 /home/admin/web/hope.domain.com/public_html/app/controllers/IndexController.php(75): admin\HomeController->actionIndex() #3 /home/admin/web/hope.domain.com/public_html/app/controllers/GeneralController.php(19): IndexController->run('actionIndex') #4 /home/admin/web/hope.domain.com/public_html/core/classes/System/Router.php(148): GeneralController->run in /home/admin/web/hope.domain.com/public_html/core/classes/System/ObjectModel.php on line 655

**Comment by spike99** [comment]
In user account we have
Warning: count(): Parameter must be an array or an object that implements Countable in /home/admin/web/hope.domain.com/public_html/app/controllers/front/FrontController.php on line 80

**Comment by vityabond** [comment]
> In user account we have
> Warning: count(): Parameter must be an array or an object that implements Countable in /home/admin/web/hope.domain.com/public_html/app/controllers/front/FrontController.php on line 80
I've fixed it.
