### ISSUE TITLE
No connectin with MySQL

### ISSUE THREAD

**Issue by xodroid** [vityabond/hopebilling#15]
Is Hopebilling compatible with Mariadb? I use Mariadb 10.1.44 and Php 7.0.33. During install at Step 3, I get No connectin with MySQL even when the details I enter are correct.

Do I have to input the DB login somewhere in a config.php file in install directory?

**Comment by sohamb03** [comment]
Does work for me, check if your host details are correct.

**Comment by xodroid** [comment]
Works with cPanel but on a vps with another panel, it does not

**Comment by xodroid** [comment]
May I send you a panel shared account to try install HB @vityabond ?

**Comment by sohamb03** [comment]
@xodroid Drop him an email on `vityabond@gmail.com`
