### ISSUE TITLE
Web Hosting

### ISSUE THREAD

**Issue by nightstryke** [vityabond/hopebilling#16]
@vityabond 
I use DirectAdmin on my Servers.
But with DirectAdmin and cPanel both have Shared Hosting and Reseller Hosting.
How do we configure that with HopeBilling?

**Comment by sohamb03** [comment]
DirectAdmin is supported in HopeBilling -

```Web hosting (vestacp, cpanel, ispmanager, cpanel, plask, ispconfig, directadmin)```

You can configure connection to your server in the HopeBilling Admin Area under the hosting section.

**Comment by nightstryke** [comment]
> DirectAdmin is supported in HopeBilling -
> 
> `Web hosting (vestacp, cpanel, ispmanager, cpanel, plask, ispconfig, directadmin)`
> 
> You can configure connection to your server in the HopeBilling Admin Area under the hosting section.

Yes, but on the admin account I have setup for the billing panel.
There's two different sets of hosting plans:

1. For **Reselling**
2. For **Shared** Hosting

HopeBilling isn't showing the **Reseller/Reselling** Plans, only the **Shared** Hosting Plans

**Comment by vityabond** [comment]
> > DirectAdmin is supported in HopeBilling -
> > `Web hosting (vestacp, cpanel, ispmanager, cpanel, plask, ispconfig, directadmin)`
> > You can configure connection to your server in the HopeBilling Admin Area under the hosting section.
> 
> Yes, but on the admin account I have setup for the billing panel.
> There's two different sets of hosting plans:
> 
> 1. For **Reselling**
> 2. For **Shared** Hosting
> 
> HopeBilling isn't showing the **Reseller/Reselling** Plans, only the **Shared** Hosting Plans

Hi
Can you send me access to panel for fixing it?

**Comment by xodroid** [comment]
I have HB behind Cloudflare, I added a DA server but it was stuck on that loading animation. I open admin area again in another tab, server was added. I click Check connection, again stuck. Up to now both tabs stuck on animation. Plus a lot of mcrypt php deprecated errors. It's very buggy currently.

**Comment by sohamb03** [comment]
@xodroid Use the version from GitHub. The one on the website is buggy. Just clone this repo and you'll be fine.
