### ISSUE TITLE
Accounts created without payment? 

### ISSUE THREAD

**Issue by tejli007** [vityabond/hopebilling#18]
Hello.

When a user places an order and do not pays the invoice, the cpanel creates the accounts and keeps is suspended. Once the invoice is paid the accounts is getting unsuspended. Is this a common thing or a bug? 

Second: I have selected English as language and some text is still in Russian ex. Invoices. Is a bug or is not correctly translated?

**Comment by vityabond** [comment]
It's normal. Account will be created without payment in suspended mode.
