### ISSUE TITLE
Setting Up Hopebilling 

### ISSUE THREAD

**Issue by MutegekiHenry** [vityabond/hopebilling#19]
### What I went through
I visited the official site [https://hopebilling.com/](url) and downloaded version 1.0 
I then set out to install it locally on my windows machine, having XAMMP installation (PHP 7.3.0)
I transferred the extracted folder of 1.0 to my htdocs folder in XAMMP and started the Apache server. 
I then moved to the browser to and run localhost/1.0 

### ISSUES Encounterred
 On the first attempt, I got a PHP error `Error! PHP param short_open_tag must be set as on in php.ini`
I solved this by updating my php.ini file's short_open_tag to On. 

I then reloaded the route `localhost/1.0` and it auto redirects to a new route `localhost/install` and shows the error page below with a 404 error code. Am stack at that point!  

![installError](https://user-images.githubusercontent.com/36065782/80681274-2f719100-8a75-11ea-9aa9-edbbe848adc8.PNG)

### The Big Questions! 
How can one set up Hope Billing locally 
Is there DB support like MySQL?

**Comment by MutegekiHenry** [comment]
Could someone kindly give direction on how to set up hope billing on a Linux server?

**Comment by sohamb03** [comment]
Just clone the version from GitHub and put it into your public_html directory. Then browse to the (sub)domain and follow the on-screen instructions in the Installer.

**Comment by MutegekiHenry** [comment]
ok thanks

**Comment by MutegekiHenry** [comment]
> ### What I went through
> 
> I visited the official site [https://hopebilling.com/](url) and downloaded version 1.0
> I then set out to install it locally on my windows machine, having XAMMP installation (PHP 7.3.0)
> I transferred the extracted folder of 1.0 to my htdocs folder in XAMMP and started the Apache server.
> I then moved to the browser to and run localhost/1.0
> ### ISSUES Encounterred
> 
> On the first attempt, I got a PHP error `Error! PHP param short_open_tag must be set as on in php.ini`
> I solved this by updating my php.ini file's short_open_tag to On.
> 
> I then reloaded the route `localhost/1.0` and it auto redirects to a new route `localhost/install` and shows the error page below with a 404 error code. Am stack at that point!
> 
> ![installError](https://user-images.githubusercontent.com/36065782/80681274-2f719100-8a75-11ea-9aa9-edbbe848adc8.PNG)
> ### The Big Questions!
> 
> How can one set up Hope Billing locally
> Is there DB support like MySQL?

@sohamb03 i get this same issue even on the server

**Comment by MutegekiHenry** [comment]
was the install module removed?

**Comment by sohamb03** [comment]
No, first thing first.

`short_tag_open` must be set as On, it's not an error, it's a requirement for HopeBilling. 

Second thing, HopeBilling can't live inside a subdirectory. You're bound to get 404 errors if you try that. The available options are to place all your HopeBilling files in the root domain, like `example.com` or a subdomain like `sub.domain.com` but not a subdirectory. If you need help setting up HopeBilling, I can do it in case you're not able to solve things yourself, drop me a line on email.

**Comment by MutegekiHenry** [comment]
oh that makes sense coz I was putting it in a subdirectory

**Comment by MutegekiHenry** [comment]
> No, first thing first.
> 
> `short_tag_open` must be set as On, it's not an error, it's a requirement for HopeBilling.
> 
> Second thing, HopeBilling can't live inside a subdirectory. You're bound to get 404 errors if you try that. The available options are to place all your HopeBilling files in the root domain, like `example.com` or a subdomain like `sub.domain.com` but not a subdirectory. If you need help setting up HopeBilling, I can do it in case you're not able to solve things yourself, drop me a line on email.

the more reason for needing Documentation

**Comment by sohamb03** [comment]
Well, I'm just someone helping out with this project cuz I admire it, not a Maintainer. I could create a documentation though, let's see.

**Comment by MutegekiHenry** [comment]
Thanks @sohamb03 it finally worked out

**Comment by sohamb03** [comment]
Glad to help. I'm now a collaborator on this project, so will try to setup some docs and things soon. :-)

**Comment by MutegekiHenry** [comment]
Thanks again, going to have a look at the project and see how best i could help as well

**Comment by sohamb03** [comment]
I've created the wiki, it's minimal but enough to perform the installation for now. :-)
