### ISSUE TITLE
Installation on IspConfig webspace

### ISSUE THREAD

**Issue by smilebasti** [vityabond/hopebilling#21]
Hi, first of all thanks for the wiki. I just tried to install it but it fails.
I am getting the Error 404 Not found after i turned on short_open_tag = On. 

I am using ISPConfig to host Hostbilling and installed it in the directory /web in the right domain.
Maybe i misunderstood the sub-directory part? I am running ISPConfig on Apache2 and not on Nginx. Any thoughts how to resolve this?

Thanks ahead for your help.

**Comment by sohamb03** [comment]
Yeah, install it in the root directory of your domain. For example, if you're using cPanel you'd want to place the files in the public_html/yourdomain.com folder. So you shouldn't put it in something like /web it should be in /

**Comment by smilebasti** [comment]
ok thanks. I just thought maybe to put it where the index file was before.

I have now put the all files from /web/ to / but now i am just seeing Index of / . I think that's the usual page if no index file could be located.

Any thoughts on this?

**Comment by smilebasti** [comment]
I just reinstalled it and it worked under /web
