### ISSUE TITLE
MySQL connection failed during installation

### ISSUE THREAD

**Issue by smilebasti** [vityabond/hopebilling#23]
Hi i just figured it out how to install it and during the installation-wizard after i entered the Database Credentials i am getting an strange Error. See attached picture: 
![image](https://user-images.githubusercontent.com/60941345/81577337-93ffea80-93a9-11ea-98aa-eadc80f04e92.png)

Any thoughts on that?
Thanks ahead :)

**Comment by smilebasti** [comment]
At the beginning of the setup-tour i also had this Error: Notice: unserialize(): Error at offset 0 of 1 bytes in /var/www/clients/client2/web36/web/core/classes/System/Config.php on line 32

**Comment by skynet88** [comment]
which file to change the db name,db username and pass for myqsql database???

**Comment by vityabond** [comment]
> which file to change the db name,db username and pass for myqsql database???

app/config/global.config

**Comment by smilebasti** [comment]
Hi this wasn't my original Question @vityabond. 

Do you have any thoughts on how to solve this Problem? 
Thanks

**Comment by vityabond** [comment]
> Hi this wasn't my original Question @vityabond.
> 
> Do you have any thoughts on how to solve this Problem?
> Thanks

You need disable strict mode in mysql (mariadb) config

**Comment by vityabond** [comment]
> At the beginning of the setup-tour i also had this Error: Notice: unserialize(): Error at offset 0 of 1 bytes in /var/www/clients/client2/web36/web/core/classes/System/Config.php on line 32

upload empty file to app/config/global.config

**Comment by smilebasti** [comment]
Thanks for the replies. I have disabled the strict mode but now i am getting this error: 
![image](https://user-images.githubusercontent.com/60941345/82652469-f49aed00-9c1d-11ea-9c7a-a8bf3f204804.png)

I searched the app/config/global.config and is already there. Should i replace it with an empty file?

**Comment by vityabond** [comment]
reinstall please
