### ISSUE TITLE
problems with placing hosting orders by client and setting plans by admin

### ISSUE THREAD

**Issue by kmzpius** [vityabond/hopebilling#24]

**Comment by sohamb03** [comment]
Please elaborate on the issue.

**Comment by vityabond** [comment]
I don't see problems

**Comment by kmzpius** [comment]
c panel creates accounts but user credentials can't  work. i guess the password  pattern for strength isn't fine.. because code doesn't accept the strongest password with a couple of characters but accepts a weaker one with no special characters.

and finally with some panels like plesk you can't create an account/place an order for hosting always alerting "Technical error blah blah"... what is the actual technical problem.
