### ISSUE TITLE
Wrong Credentials For Demo Dashboards In Documentation

### ISSUE THREAD

**Issue by MutegekiHenry** [vityabond/hopebilling#25]
### Problem: 
The current install [documentation](https://github.com/vityabond/hopebilling/wiki) provides wrong(Interchanged) credentials for the Admin and User Dashboard. 

### Screenshots: 
![Screenshot from 2020-05-17 14-46-53](https://user-images.githubusercontent.com/36065782/82143600-bf715200-984d-11ea-9f0a-f9f20ed1d7a9.png)

**Comment by vityabond** [comment]
> ### Problem:
> The current install [documentation](https://github.com/vityabond/hopebilling/wiki) provides wrong(Interchanged) credentials for the Admin and User Dashboard.
> 
> ### Screenshots:
> ![Screenshot from 2020-05-17 14-46-53](https://user-images.githubusercontent.com/36065782/82143600-bf715200-984d-11ea-9f0a-f9f20ed1d7a9.png)

It works.

**Comment by MutegekiHenry** [comment]
The credentials must be swapped for it to work..

**Comment by MutegekiHenry** [comment]
i could raise a simple PR to fix this

**Comment by sohamb03** [comment]
Fixed ... Sorry it was my fault. :P
