### ISSUE TITLE
Notice: unserialize(): Error at offset 0 of 1 bytes in core/classes/System/Config.php on line 32

### ISSUE THREAD

**Issue by jerocobo** [vityabond/hopebilling#32]
I get this error when I try to install it.

Notice: unserialize(): Error at offset 0 of 1 bytes in core/classes/System/Config.php on line 32

**Comment by cameronmotes** [comment]
Bump. I'm having the same issues.

Installing on VestaCP

**Comment by panuwizzle** [comment]
I can see the installation page by adding `s:0:"";` to `app/config/global.config` .
The function try to de-serialize the empty string so it shows the error.

**Comment by msrsakib** [comment]
Clear **unserialize** from the 32 No. line. It'll be fixed.

**Comment by vityabond** [comment]
fixed
