### ISSUE TITLE
Parse error: syntax error, unexpected end of file

### ISSUE THREAD

**Issue by semplon** [vityabond/hopebilling#4]
Hi, i like to try the code, when install there is error with it. 

`Parse error: syntax error, unexpected end of file in /home/username/public_html/template/install/index.php on line 297`

I am using php7.2 on Apache web server

**Comment by sohamb03** [comment]
Well, as of now, I'll unofficially trying to maintain and providing fixes for this application till I can get in touch with @vityabond. 

For your issue, please only use PHP version 7.0 or 5.6 for this application, until it can be made compatible with the latest PHP versions.

**Comment by semplon** [comment]
ah i see, i will try it then. thanks.

**Comment by sohamb03** [comment]
If you're interested in helping me translate a few parts into English that have only been partially translated, feel free to drop me an email on sohamb03@outlook.com or join my Discord (https://discord.gg/HWg6uQy - @sohamb03#0001) and DM me.

Don't worry it hardly requires any coding skills and I'll tell you all you've to do, not difficult at all. It's just that I'm still a high school student, and can't spare much time for all this. :-)

**Comment by sohamb03** [comment]
If you're interested in helping me translate a few parts into English that have only been partially translated, feel free to drop me an email on sohamb03@outlook.com or join my Discord (https://discord.gg/HWg6uQy - `@sohamb03#0001`) and DM me.

Don't worry it hardly requires any coding skills and I'll tell you all you've to do, not difficult at all. It's just that I'm still a high school student, and can't spare much time for all this. :-)

**Comment by vityabond** [comment]
> Well, as of now, I'll unofficially trying to maintain and providing fixes for this application till I can get in touch with @vityabond.
> 
> For your issue, please only use PHP version 7.0 or 5.6 for this application, until it can be made compatible with the latest PHP versions.

You can write me to vityabond@gmail.com

**Comment by semplon** [comment]
@sohamb03 okay, i will contact you

@vityabond hello, as for my test. this application cannot be installed under folder. when i install it under folder http://localhost/billing/ it always redirect to http://localhost/install which is not exist. 

i think you should rewrite the router to handle with folder.

thanks

**Comment by sohamb03** [comment]
@vityabond Sure, will get back to you. 

@semplon Well you'll have to put the files in the root directory. That installation can't exist in a subfolder. You can do the Installation on a subdomain rather, if you don't wanna use your root domain.

**Comment by semplon** [comment]
@sohamb03 i think the code should can handle both in subfolder on in main root. yes i do aware that i can install it on the root directory. and i did. it's better if we can install it inside folders.

**Comment by sohamb03** [comment]
Well I'd tried to put it inside a subfolder, but it turned out that the Installer reads the root domain as the Installation direction instead of the given subfolder. That's why I assumed it can't be done inside of a subfolder. Ofc it's good if it can be done, but presently I'm doing it in a subdomain. :-)
