### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by GaneshKandu** [vityabond/hopebilling#43]
Hi Trying to install HopeBilling but getting error
using php 7.3

```
Notice: unserialize(): Error at offset 0 of 1 bytes in core/classes/System/Config.php on line 32 Warning: Cannot modify header information - headers already sent by (output started at core/classes/System/Config.php:32) in core/classes/System/Tools.php on line 27 
```

**Comment by luixinlbtk** [comment]
where did you get the installer? I can't find him, could you send it to me? Thanks a lot

**Comment by GaneshKandu** [comment]
i have downloaded from https://hopebilling.com/
download button
its a master download of github

**Comment by GaneshKandu** [comment]
Adding empty serialized array in ``app/config/global.config`` works

**Comment by GaneshKandu** [comment]
you need to add that in all config because i am getting same error in setting page

**Comment by luixinlbtk** [comment]
> i have downloaded from https://hopebilling.com/
> download button
> its a master download of github

I downloaded it but I get the same error,. I see that the install folder is missing

**Comment by Muhamadanwar001** [comment]
hello,im sorry, error same

**Comment by vityabond** [comment]
fixed
