### ISSUE TITLE
Notice: unserialize(): Error at offset 0 of 1 bytes in /home/billing99/public_html/core/classes/System/Config.php on line 32

### ISSUE THREAD

**Issue by totaltrader** [vityabond/hopebilling#48]
Warning: Cannot modify header information - headers already sent by (output started at /home/billing99/public_html/core/classes/System/Config.php:32) in /home/billing99/public_html/core/classes/System/Tools.php on line 27

Really like the  script, but install it is very tedious, will be happy and ready to support any developer that expend time  fixing it, to make a clean easy to install and configure this wonderful script.

**Comment by insxa** [comment]
Try to delete from app/modules billmanagervps.zip

**Comment by vityabond** [comment]
исправлено
