### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Esolein** [vityabond/hopebilling#49]
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'date' in C:\xampp\htdocs\core\classes\System\Db\Schema\Table.php:117 Stack trace: #0 C:\xampp\htdocs\core\classes\System\Db\Schema\Table.php(117): PDOStatement->execute() #1 C:\xampp\htdocs\core\classes\System\Db\Schema\Schema.php(20): System\Db\Schema\Table->create() #2 C:\xampp\htdocs\app\controllers\InstallController.php(211): System\Db\Schema\Schema::create('hosting_account...', Object(Closure)) #3 C:\xampp\htdocs\app\controllers\InstallController.php(46): InstallController->actionDb() #4 C:\xampp\htdocs\core\classes\System\Router.php(148): InstallController->run('actionIndex', Array, 'install') #5 C:\xampp\htdocs\index.php(7): System\Router->run() #6 {main} thrown in C:\xampp\htdocs\core\classes\System\Db\Schema\Table.php on line 117

Anyone has the Mysql database ??? 
Installer are broken

**Comment by Esolein** [comment]
#push

**Comment by Esolein** [comment]
#PUSH

**Comment by Esolein** [comment]
PUSH

**Comment by BunkDev5674** [comment]
i am getting same issue and it is annoying


Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'date' in /home/admin/web/clients.sparklehosting.org/public_html/core/classes/System/Db/Schema/Table.php:117 Stack trace: #0 /home/admin/web/clients.sparklehosting.org/public_html/core/classes/System/Db/Schema/Table.php(117): PDOStatement->execute() #1 /home/admin/web/clients.sparklehosting.org/public_html/core/classes/System/Db/Schema/Schema.php(20): System\Db\Schema\Table->create() #2 /home/admin/web/clients.sparklehosting.org/public_html/app/controllers/InstallController.php(211): System\Db\Schema\Schema::create('hosting_account...', Object(Closure)) #3 /home/admin/web/clients.sparklehosting.org/public_html/app/controllers/InstallController.php(46): InstallController->actionDb() #4 /home/admin/web/clients.sparklehosting.org/public_html/core/classes/System/Router.php(148): InstallController->run('actionIndex', Array, 'install') #5 /home/admin/web/clients.sparklehosting.org/public_html/index.php(7): Syste in /home/admin/web/clients.sparklehosting.org/public_html/core/classes/System/Db/Schema/Table.php on line 117

**Comment by BunkDev5674** [comment]
Hi i found the soloution! https://www.knowledgebase-script.com/kb/article/how-do-i-disable-strict-mode-in-mysql-163.html
gotta disable safe mode!

**Comment by vityabond** [comment]
Yeah, need disable Strict Mode
