### ISSUE TITLE
/core/classes/System/Db/Schema/Table.php on line 117

### ISSUE THREAD

**Issue by Draco-Zero** [vityabond/hopebilling#5]
After 3 steps of installation, when filling in the database on the page, this error appears. How to resolve it?
`Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'date' in /home/admin/web/billing.dracoblog.ru/public_html/core/classes/System/Db/Schema/Table.php:117 Stack trace: #0 /home/admin/web/billing.dracoblog.ru/public_html/core/classes/System/Db/Schema/Table.php(117): PDOStatement->execute() #1 /home/admin/web/billing.dracoblog.ru/public_html/core/classes/System/Db/Schema/Schema.php(20): System\Db\Schema\Table->create() #2 /home/admin/web/billing.dracoblog.ru/public_html/app/controllers/InstallController.php(211): System\Db\Schema\Schema::create('hosting_account...', Object(Closure)) #3 /home/admin/web/billing.dracoblog.ru/public_html/app/controllers/InstallController.php(46): InstallController->actionDb() #4 /home/admin/web/billing.dracoblog.ru/public_html/core/classes/System/Router.php(148): InstallController->run('actionIndex', Array, 'install') #5 /home/admin/web/billing.dracoblog.ru/public_html/index.php(7): System\Router->run() #6 {main} thrown in /home/admin/web/billing.dracoblog.ru/public_html/core/classes/System/Db/Schema/Table.php on line 117`

**Comment by vityabond** [comment]
hi, disable mysql strict mode
