### ISSUE TITLE
Заброшено?

### ISSUE THREAD

**Issue by PEKKAch4KA** [vityabond/hopebilling#50]
Привет, панель заброшена? И кто смог установить дайте контакты

**Comment by sliine** [comment]
Скорее всего, что да ибо как я вижу по обновлениям, разрабам плевать совсем.

**Comment by sliine** [comment]
> Привет, панель заброшена? И кто смог установить дайте контакты

Напиши мне в телеграмм, https://t.me/sline_gg 
Я вроде понял причину

**Comment by vityabond** [comment]
поправил установщик

**Comment by sliine** [comment]
> поправил установщик

Интересно вы работаете...

**Comment by ImOstrovskiy** [comment]
> > поправил установщик
> 
> Интересно вы работаете...

++
