### ISSUE TITLE
run in xampp

### ISSUE THREAD

**Issue by famousman** [vityabond/hopebilling#51]
hi I wanted to test hopebilling by xampp but i got this error with tried to change the root in setting.php
​
System\Router
Fatal error: Uncaught Error: Class 'System\Router' not found in D:\xampp\htdocs\hbill\index.php:6 Stack trace: #0 {main} thrown in D:\xampp\htdocs\hbill\index.php on line 6

**Comment by vityabond** [comment]
you need apache module mod_rewrite
