### ISSUE TITLE
Documentation and Support Website not working

### ISSUE THREAD

**Issue by smilebasti** [vityabond/hopebilling#9]
Hi, i was looking for this software a long time but as i was checking the Documentation-Link i could only see the domain. As i wanted to contact support i also could because after clicking on open new ticket it failed.
I wanted to ask if there is documentation on how to integrate Hopebilling with Ispconfig and if this project is still active?

**Comment by vityabond** [comment]
The project is active. No documentation yet.

**Comment by aacosae** [comment]
Please advise us with the Installation steps

**Comment by keaza** [comment]
@aacosae Honestly i thought the installation was super easy, drag and drop the files, then go to the place where you placed the files in a web browser, and it guides you through.... dont know how much harder it can get?

**Comment by MutegekiHenry** [comment]
> 
> 
> @aacosae Honestly i thought the installation was super easy, drag and drop the files, then go to the place where you placed the files in a web browser, and it guides you through.... dont know how much harder it can get?

Been there, done that, failed at it!  guess am not alone. Documentation of basic installation would really come in handy

**Comment by sohamb03** [comment]
Please take a look at https://github.com/vityabond/hopebilling/wiki

**Comment by smilebasti** [comment]
Thanks a lot for the Wiki

**Comment by sohamb03** [comment]
No problem, that's only a basic one for now, I'll improve it when I'm free. :-)
